### ISSUE TITLE
Why its download 100 comments only ?

### ISSUE THREAD

**Issue by VinayChaudhari1996** [ahmedshahriar/youtube-comment-scraper#1]
Hi,

It's a really nice script but, when we run it for a particular video,  script is not able to collect  total number of comments present for a given video.

It always download approx 100 videos. How can we fix it?

Thanks

**Comment by ahmedshahriar** [comment]
Hello @VinayChaudhari1996,

I set the default download limit to 100. That's why it happened.
You can change it. I updated the script.

Please check line number 41 in the script  [ytb_comment_scraper.py](https://github.com/ahmedshahriar/youtube-comment-scraper/blob/main/ytb_comment_scraper.py),
set the value of the variable "COMMENT_LIMIT" as you wish.

Hopefully, the issue will be resolved after this. I'm closing this issue.
Please let me know if anything is needed. 
Thanks

**Comment by VinayChaudhari1996** [comment]
Thanks lots 😇 @ahmedshahriar

**Comment by ahmedshahriar** [comment]
> Thanks lots 😇 @ahmedshahriar

Pleasure 😀

**Comment by VinayChaudhari1996** [comment]
> Hello @VinayChaudhari1996,
> 
> I set the default download limit to 100. That's why it happened.
> You can change it. I updated the script.
> 
> Please check line number 41 in the script [ytb_comment_scraper.py](https://github.com/ahmedshahriar/youtube-comment-scraper/blob/main/ytb_comment_scraper.py),
> set the value of the variable "COMMENT_LIMIT" as you wish.
> 
> Hopefully, the issue will be resolved after this. I'm closing this issue.
> Please let me know if anything is needed.
> Thanks




> Hello @VinayChaudhari1996,
> 
> I set the default download limit to 100. That's why it happened.
> You can change it. I updated the script.
> 
> Please check line number 41 in the script [ytb_comment_scraper.py](https://github.com/ahmedshahriar/youtube-comment-scraper/blob/main/ytb_comment_scraper.py),
> set the value of the variable "COMMENT_LIMIT" as you wish.
> 
> Hopefully, the issue will be resolved after this. I'm closing this issue.
> Please let me know if anything is needed.
> Thanks

Now , There is one more issue again , number of comments downloading mismatch.

**Comment by ahmedshahriar** [comment]
> > Hello @VinayChaudhari1996,
> > I set the default download limit to 100. That's why it happened.
> > You can change it. I updated the script.
> > Please check line number 41 in the script [ytb_comment_scraper.py](https://github.com/ahmedshahriar/youtube-comment-scraper/blob/main/ytb_comment_scraper.py),
> > set the value of the variable "COMMENT_LIMIT" as you wish.
> > Hopefully, the issue will be resolved after this. I'm closing this issue.
> > Please let me know if anything is needed.
> > Thanks
> 
> > Hello @VinayChaudhari1996,
> > I set the default download limit to 100. That's why it happened.
> > You can change it. I updated the script.
> > Please check line number 41 in the script [ytb_comment_scraper.py](https://github.com/ahmedshahriar/youtube-comment-scraper/blob/main/ytb_comment_scraper.py),
> > set the value of the variable "COMMENT_LIMIT" as you wish.
> > Hopefully, the issue will be resolved after this. I'm closing this issue.
> > Please let me know if anything is needed.
> > Thanks
> 
> Now , There is one more issue again , number of comments downloading mismatch.

Hello @VinayChaudhari1996,
All should be cleared by now. Please check
